import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="nl">
      <body className={`${inter.className} min-h-screen flex flex-col`}>
        <div className="p-4 bg-emerald-700 flex gap-4">
        <Link href='/about' className=''>About Me</Link>
        <Link href='/contact' className=''>Contact</Link>
        </div>

        <main id="main-content" className="flex-1">
          {children}
        </main>
      </body>
    </html>
  );
}
